### ISSUE TITLE
Config land-creation only-leaders still has no effect

### ISSUE THREAD

**Issue by Sogekeeper** [RoinujNosde/SimpleClans#258]
Plugin version: Build #193 (Sat Sep 25 19:27:29 UTC 2021) **(Jenkins)**
Server runs the latest version of Magma for 1.12.2

Server is using enable-auto-groups and auto-group-groupname.
Vault, LuckPerms and GriefPrevention are installed.

The following config still has no effect. A player with no clan or any other status other than leader (group sc_untrusted, sc_trusted and default from luckperms) can still use the golden shovel to create GriedPrevention lands.

`land-creation:
    only-leaders: true`

I have tried joining the server and using the shovel = The shovel works
Tried accepting the invitation to become a member of a clan = The shovel works

If I need to provide any other info please let me know

**Comment by Tomut0** [comment]
Hello there. 
It would be more **faster** to recognize the problem, if you will send your configuration file.

**Comment by Sogekeeper** [comment]
Hi there,
Here you go, my config.yml for SimpleClans

EDIT: Oops, seems like Github doesn't fold code sections, here's a txt file
[SimpleClans_Config.txt](https://github.com/RoinujNosde/SimpleClans/files/7245291/SimpleClans_Config.txt)

```
safe-civilians: false
tag:
  default-color: '8'
  max-length: 5
  bracket:
    color: '8'
    leader-color: '4'
    left: ''
    right: ''
  min-length: 2
  separator:
    color: '8'
    leader-color: '4'
    char: ' .'
settings:
  enable-gui: true
  disable-messages: false
  tameable-mobs-sharing: false
  teleport-blocks: false
  teleport-home-on-spawn: false
  drop-items-on-clan-home: false
  keep-items-on-clan-home: false
  item-list: []
  show-debug-info: false
  enable-auto-groups: true
  chat-compatibility-mode: true
  rival-limit-percent: 50
  use-colorcode-from-prefix-for-name: true
  display-chat-tags: true
  global-friendly-fire: true
  unrivable-clans:
  - admin
  - staff
  - mod
  show-unverified-on-list: false
  blacklisted-worlds: []
  banned-players: []
  disallowed-tags:
  - vip
  - clan
  language: en
  user-language-selector: true
  disallowed-tag-colors:
  - '4'
  server-name: '&4RecintoDoLordValdemiro'
  new-clan-verification-required: true
  allow-regroup-command: true
  allow-reset-kdr: false
  rejoin-cooldown: 25200
  rejoin-cooldown-enabled: true
  accept-other-alphabets-letters-on-tag: false
  ranking-type: DENSE
  list-default-order-by: kdr
  lore-length: 36
war-and-protection:
  war-enabled: true
  land-sharing: true
  protection-providers:
  - WorldGuardProvider
  - WorldGuard6Provider
  - PlotSquared5Provider
  - PlotSquared3Provider
  - GriefPreventionProvider
  listeners:
    priority: HIGHEST
    ignored-list:
      PLACE:
      - PLAYER_HEAD
      BREAK:
      - EMERALD_BLOCK
  set-base-only-in-land: false
  war-normal-expiration-time: 0
  war-disconnect-expiration-time: 5
  edit-all-lands: false
  land-creation:
    only-leaders: true
    only-one-per-clan: true
  war-actions:
    CONTAINER: true
    INTERACT: true
    BREAK: true
    PLACE: true
    DAMAGE: true
    INTERACT_ENTITY: true
  war-start:
    request-enabled: true
    members-online-max-difference: 5
kdr-grinding-prevention:
  enable-max-kills: true
  max-kills-per-victim: 1
  enable-kill-delay: false
  delay-between-kills: 5
commands:
  more: scmore
  ally: scally
  clan: clan
  accept: scaccept
  deny: scdeny
  global: scglobal
  clan_chat: .
  force-priority: true
economy:
  creation-price: 100.0
  purchase-clan-create: false
  verification-price: 1000.0
  purchase-clan-verify: false
  invite-price: 20.0
  purchase-clan-invite: false
  home-teleport-price: 5.0
  purchase-home-teleport: false
  home-teleport-set-price: 5.0
  purchase-home-teleport-set: false
  home-regroup-price: 5.0
  purchase-home-regroup: false
  unique-tax-on-regroup: true
  issuer-pays-regroup: true
  money-per-kill: false
  money-per-kill-kdr-multipier: 10
  purchase-reset-kdr: true
  reset-kdr-price: 10000.0
  purchase-member-fee-set: false
  member-fee-set-price: 1000.0
  member-fee-enabled: false
  member-fee-last-minute-change-interval: 8
  max-member-fee: 200.0
  upkeep: 200.0
  upkeep-enabled: false
  multiply-upkeep-by-clan-size: false
  charge-upkeep-only-if-member-fee-enabled: true
  bank-log:
    enable: true
kill-weights:
  rival: 2.0
  civilian: 0.0
  neutral: 1.0
  ally: -1.0
  deny-same-ip-kills: false
clan:
  homebase-teleport-wait-secs: 10
  homebase-can-be-set-only-once: true
  min-size-to-set-rival: 3
  max-length: 25
  max-description-length: 120
  min-description-length: 10
  max-members: 25
  confirmation-for-promote: false
  trust-members-by-default: false
  confirmation-for-demote: false
  percentage-online-to-demote: 100.0
  ff-on-by-default: true
  min-length: 2
  max-alliances: -1
  min-size-to-set-ally: 3
  min-to-verify: 1
tasks:
  collect-upkeep:
    hour: 1
    minute: 30
  collect-upkeep-warning:
    hour: 12
    minute: 0
  collect-fee:
    hour: 1
    minute: 0
page:
  untrusted-color: '8'
  clan-name-color: b
  subtitle-color: '7'
  headings-color: '8'
  trusted-color: f
  leader-color: '4'
  separator: '-'
  size: 100
clanchat:
  enable: true
  tag-based-clan-chat: false
  announcement-color: e
  format: '&b[%clan%&b] &4<%nick-color%%player%&4> %rank%: &b%message%'
  spy-format: '&8[Spy] [&bC&8] <%clean-tag%&8> <%nick-color%*&8%player%>&8 %rank%&8:
    %message%'
  rank: '&f[%rank%&f]'
  leader-color: '4'
  trusted-color: f
  member-color: '7'
request:
  message-color: b
  ask-frequency-secs: 60
  max-asks-per-request: 1440
bb:
  color: e
  accent-color: '8'
  show-on-login: true
  size: 6
  login-size: 6
allychat:
  enable: true
  format: '&b[Ally Chat] &4<%clan%&4> <%nick-color%%player%&4> %rank%: &b%message%'
  spy-format: '&8[Spy] [&cA&8] <%clean-tag%&8> <%nick-color%*&8%player%>&8 %rank%&8:
    %message%'
  rank: '&f[%rank%&f]'
  leader-color: '4'
  trusted-color: f
  member-color: '7'
discordchat:
  enable: false
  discord-format: '%player% » %message%'
  format: '&b[&9D&b] &b[%clan%&b] &4<%nick-color%%player%&4> %rank%: &b%message%'
  spy-format: '&8[Spy] [&9D&8] <%clean-tag%&8> <%nick-color%*&8%player%>&8 %rank%&8:
    %message%'
  rank: '[%rank%]'
  leader-role: Leader
  leader-color: 231, 76, 60, 100
  leader-id: 0
  text:
    category-format: SC - TextChannels
    category-ids: []
    whitelist: []
    clans-limit: 100
purge:
  inactive-player-data-days: 30
  inactive-clan-days: 7
  unverified-clan-days: 2
mysql:
  username: ''
  host: localhost
  port: 3306
  enable: false
  password: ''
  database: ''
permissions:
  auto-group-groupname: true
  YourClanNameHere:
  - test.permission
performance:
  save-periodically: true
  save-interval: 10
  use-threads: true
  use-bungeecord: false
```

**Comment by RoinujNosde** [comment]
![image](https://user-images.githubusercontent.com/6441328/135174785-59fec4c1-5d16-4d4c-ba5d-7d32a700c3f8.png)
Just tested it and the setting is working fine.

**Comment by RoinujNosde** [comment]
Did you get any errors in your console?

**Comment by Sogekeeper** [comment]
Hmmm, actually I do, but it wasn't red so I didn't even notice xD

It says it couldn't find the GriefPrevention provider. Is this something else that is not part of the default GriefPrevention plugin?

![simpleclans_provider_error](https://user-images.githubusercontent.com/46176324/135176876-0865d807-c75a-4510-852d-644286a429e7.png)

**Comment by RoinujNosde** [comment]
Enable debug in SimpleClans config to know the reason.
`show-debug-info: true`

**Comment by Sogekeeper** [comment]
I have no idea why i'm missing me.ryanhamshire.GriefPrevention.Claim.getOwnerID
![image](https://user-images.githubusercontent.com/46176324/135186566-509345e9-8867-45c5-a5ac-1395be23c24a.png)

**Comment by RoinujNosde** [comment]
Update your GriefPrevention.
Your version doesn't support UUID.

**Comment by Sogekeeper** [comment]
Then I think I won't be able to use it since I'm on mc 1.12.2. If I get the latest GriefPrevention jar then the GriefPrevention simply does nothing and whenever I right click anything with any item in my hand I get this error:

![image](https://user-images.githubusercontent.com/46176324/135190178-ad8ce9fd-3e76-4675-a598-177fafc139f2.png)


GriefPrevention itself also doesn't print anything in the console while using the latest version. It doesn't even generate a folder in the plugins folder. But at least that one's on me.

**Comment by RoinujNosde** [comment]
Downgrade GP to the version for 1.12 and test SimpleClans' latest build.

**Comment by Sogekeeper** [comment]
hm, so 2 things happened, but before anything else, I'm using GP version 16.8 (the latest 1.12 according to Bukkit)

The first thing is this exception
![image](https://user-images.githubusercontent.com/46176324/135196272-7528d0ad-37cb-40e7-859c-81bc2b5781c3.png)

The second thing is that whenever I right anything while holding anything I get "Denied action", but nothing changes ingame, the right click for anything works, creating claims or eating stuff. 
Then right at the bottom of this image is what was printed when I finally right clicked the second border of the claim to create it.
![image](https://user-images.githubusercontent.com/46176324/135196648-744a05ba-dd93-4bd0-a617-7378f491d4be.png)

**EDIT: That actually happen when I do anything, breaking blocks or clicking anything with any button**
![image](https://user-images.githubusercontent.com/46176324/135197912-b90fd7f4-bf5a-41c4-bc06-9a5fa24ef44a.png)

**Comment by Sogekeeper** [comment]
There's something else, this also showed up

![image](https://user-images.githubusercontent.com/46176324/135198693-70b77e74-b4f3-425a-beb0-cb48efd1647f.png)

**Comment by RoinujNosde** [comment]
"Denied action" is misleading. It actually means SimpleClans didn't intervene in the action.

The real problem is that error: NoClassDefFoundError.
It seems your version of GP doesn't have an essential class for blocking land claiming.

**Comment by RoinujNosde** [comment]
https://dev.bukkit.org/projects/grief-prevention/files/2613336
The event for blocking land claiming was added in this version, but it's for 1.13

**Comment by Sogekeeper** [comment]
Well, RIP me, I just tried 16.9 to see if it works with 1.12 by any chance and it didn't. GP Doesn't work and the error below shows up.

But since that "Denied action" log disappears if I set  `show-debug-info: false` then I don't think this will be that much of a problem anymore thanks to that other change to how auto-groups work, I can just bind griefprevention.claims to sc_leader and be happy (I think, haven't tested it yet). 

I've also figured it out that if we use /clan lookup [player] we have an easy way to know if someone disbanded their clan to have an impenetrable land.

![image](https://user-images.githubusercontent.com/46176324/135275881-ccfb0ee4-7140-455a-a379-3d261c469aeb.png)

**Comment by RoinujNosde** [comment]
![image](https://user-images.githubusercontent.com/6441328/135367132-31a060af-dc88-4eb3-9e30-b86dce5697dc.png)
I've also fixed this error.

Since you found a way with auto-groups, I will be closing this issue (you can re-open if it doesn't work).

> I've also figured it out that if we use /clan lookup [player] we have an easy way to know if someone disbanded their clan to have an impenetrable land.

I will see if I can delete claims when a clan is disbanded/someone leaves the clan.
